using System.Text;

public static class FactorialExercise
{
    /// <summary>
    /// Entry point for the Factorial exercise.
    /// Manages input, applies safe limits for calculation, and triggers the process.
    /// </summary>
    public static void Run()
    {
        #region Input And Validation
        Console.Write("Enter a positive integer to calculate its factorial: ");
        string userInput = Console.ReadLine()!;

        // Validate that the input is a valid integer
        if (string.IsNullOrWhiteSpace(userInput) || !int.TryParse(userInput, out int factorialNumber))
        {
            Console.WriteLine("Invalid input. Please enter a valid whole number.");
            return;
        }

        // Factorials are mathematically undefined for negative numbers in this context
        if (factorialNumber < 0)
        {
            Console.WriteLine("Error: Please enter a non-negative integer.");
            return;
        }

        /*
           SAFETY LIMIT:
           Factorials grow exponentially. 20! is the largest value a 'long' (64-bit integer)
           can hold. 21! would cause an 'overflow,' resulting in a wrong/negative number.
        */
        if (factorialNumber > 20)
        {
            Console.WriteLine("Error: Factorials above 20! will overflow and produce incorrect results.");
            Console.WriteLine("Maximum safe value is 20.");
            return;
        }
        #endregion Input And Validation

        #region Calculation And Display
        CalculateAndDisplayFactorial(factorialNumber);
        #endregion Calculation And Display
    }

    /// <summary>
    /// Calculates the factorial and constructs a visual representation of the steps (e.g., 1 x 2 x 3).
    /// </summary>
    /// <param name="targetNumber">The number to calculate (must be between 0 and 20).</param>
    static void CalculateAndDisplayFactorial(int targetNumber)
    {
        // Special case: The factorial of 0 is mathematically defined as 1
        if (targetNumber == 0)
        {
            Console.WriteLine("0! = 1");
            return;
        }

        // Use 'long' to handle the massive numbers generated by factorials
        long factorial = 1;

        /*
           StringBuilder is a professional tool used for efficient string building.
           Unlike normal strings, it doesn't create a new object in memory every
           time you add text, making it much faster inside loops.
        */
        var displayBuilder = new StringBuilder();

        for (int i = 1; i <= targetNumber; i++)
        {
            // Perform the cumulative multiplication
            factorial *= i;

            // Logic to add the " x " separator only between numbers, not at the start
            if (displayBuilder.Length > 0)
            {
                displayBuilder.Append(" x ");
            }

            displayBuilder.Append(i);
        }

        // Output the final construction: "1 x 2 x 3... = Result"
        Console.WriteLine($"{displayBuilder} = {factorial}");
    }
}